import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./(shared)/Navbar";
import Footer from "./(shared)/Footer";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body> 
    </html>
  );
}
